
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  3rd-brian

Transform:
- AWS::Serverless-2016-10-31


Resources:

  lambdaHandler:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs22.x
      Architectures:
      - arm64
      MemorySize: 256
      Timeout: 100
      CodeUri: dist-bundle/
      Environment:
        Variables:
          NODE_ENV: ''
          PG_HOST: ''
          PG_PORT: ''
          PG_DB: ''
          PG_USER: ''
          PG_PASSWORD: ''
          OPENAI_API_KEY: ''
      Events:
        ProxyApiGreedy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY


  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
Outputs:
  WebEndpoint:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
